#!/usr/bin/env python3
"""
Build a minimal "glyphless" TrueType font used for the invisible OCR text
layer in generated PDFs.

Why this exists
---------------
A searchable PDF is a page image with a layer of *invisible* text drawn on
top of it, positioned over the words it transcribes. For the text to be
selectable and searchable in every viewer, the PDF needs a real font object
with a ToUnicode CMap. But the glyphs are never painted (text render mode 3),
so the font only has to exist -- it does not need outlines for Devanagari,
Tamil, Bengali or anything else.

That is a huge win for Indic scripts: embedding real Noto fonts for 14
scripts would add many megabytes per PDF. Instead every CID maps to a single
blank glyph, and the ToUnicode CMap carries the actual Unicode text. Word
positioning is handled by the PDF writer with horizontal scaling (Tz).

Output: js/core/glyphless-font.js  (base64 of a ~1.5 KB TTF)
"""
import base64
import os
import sys

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

UPM = 1000
ADVANCE = 500  # every CID advances 0.5 em; the PDF writer scales with Tz


def build() -> bytes:
    glyph_order = [".notdef", "space"]

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap({0x0020: "space"})

    pen = TTGlyphPen(None)  # no contours == invisible
    empty = pen.glyph()
    fb.setupGlyf({name: empty for name in glyph_order})

    fb.setupHorizontalMetrics({name: (ADVANCE, 0) for name in glyph_order})
    fb.setupHorizontalHeader(ascent=800, descent=-200, lineGap=0)

    fb.setupNameTable({
        "familyName": "GlyphLessFont",
        "styleName": "Regular",
        "fullName": "GlyphLessFont",
        "psName": "GlyphLessFont",
        "version": "Version 1.000",
        "uniqueFontIdentifier": "GlyphLessFont-1.000",
    })
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800,
                usWinDescent=200, achVendID="NONE")
    fb.setupPost(isFixedPitch=1)
    fb.setupDummyDSIG()

    import io
    buf = io.BytesIO()
    fb.save(buf)
    return buf.getvalue()


def main() -> None:
    data = build()
    b64 = base64.b64encode(data).decode("ascii")

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "js", "core", "glyphless-font.js")

    lines = [b64[i:i + 100] for i in range(0, len(b64), 100)]
    body = "\n  '" + "' +\n  '".join(lines) + "'"

    with open(out, "w", encoding="utf-8") as fh:
        fh.write(
            "// Generated by tools/make_glyphless_font.py -- do not edit.\n"
            "// A ~%d byte TrueType font with a single blank glyph. Every CID in the\n"
            "// invisible OCR text layer maps to it, so a searchable PDF carries real\n"
            "// Unicode (via ToUnicode) for any Indic script without embedding a single\n"
            "// script font.\n"
            "export const GLYPHLESS_FONT_B64 =%s;\n" % (len(data), body)
        )

    print("wrote %s (%d byte font, %d byte base64)" % (out, len(data), len(b64)))


if __name__ == "__main__":
    sys.exit(main())
